license="MIT License"
modLoader="javafml" #mandatory
loaderVersion="[35, 36,)" #mandatory
issueTrackerURL="https://github.com/CodenameRevy/Additional-Bars/issues" #optional

[[mods]] #mandatory
modId="additionalbarsbyg" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Additional Bars (Oh the Biomes you'll go Addon)" #mandatory
displayURL="codenamerevy.github.io" #optional
logoFile="logo.png" #optional
credits='''
CodenameRevy (Mod Developer),
ruchom4u (Spanish Translations),
fantasyair18 (Chinese Traditional (Taiwan) Translations),
TheDirectorX, BardinTheDwarf (Russian Translations),
Zijuna (German Translations),
justmonika (Simple Chinese Translations),
mindy15963 (Korean Translations),
WadeMason''' #optional
authors="CodenameRevy" #optional
description='''
This mod adds additional bars to the game that go along with Iron Bars!
'''

[[dependencies.additionalbarsbyg]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35, 36,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.additionalbarsbyg]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,)"
    ordering="NONE"
    side="BOTH"
